### ISSUE TITLE
Heart tracking for daytime monitoring

### ISSUE THREAD

**Issue by GaryM0101** [thiswillbeyourgithub/sleep_tracker_pinetime_wasp-os#10]
Could sleeptk have the ability to track heart rate only? In any case this ability would be good for long term logging during the daylight hours.

**Comment by thiswillbeyourgithub** [comment]
Hi!
So you should go to this repo and take a look at this function :https://github.com/thiswillbeyourgithub/wasp-os/blob/authors_version/wasp/wasp.py#L701 

IIRC it was working okay but I stopped working on it when I noticed that the measurements were off.

You need to look at the settings app too that allows to tweak the periodicity.

Good luck reimplementing this!
