### ISSUE TITLE
Screen repeatedly redrawing

### ISSUE THREAD

**Issue by lukearcus** [thiswillbeyourgithub/sleep_tracker_pinetime_wasp-os#3]
Running tracking on pinetime, after attemping first hr reading, screen continuously redraws. Can't stop tracking since screen redraws over confirmation dialogue.

https://user-images.githubusercontent.com/45366909/178742377-a0624026-e5f9-43ca-a4e6-5d52555a1cad.mp4

**Comment by lukearcus** [comment]
Yeah, this is the latest version of SleepTk and uses your fork. I did actually reenable the step counter in the quick ring, but will retry with that disabled and see if there are any changes. Does work in the sim when I tried that.

**Comment by thiswillbeyourgithub** [comment]
Can you confirm that the app is working fine with heart rate tracking disabled?

**Comment by lukearcus** [comment]
Seems to be working fine, had some issues with the smart alarm, but can see that's been removed in more recent versions (I'm having a few troubles getting the watch to update, but will try and figure that out).

**Comment by thiswillbeyourgithub** [comment]
Thanks for the feedback. Now that I made it compatible with the original wasp-os without modification the only issue you should have is to make sure there is enough room for it :)
