### ISSUE TITLE
Workaround for: firmware.elf section `.text' will not fit in region `FLASH_TEXT' error

### ISSUE THREAD

**Issue by GaryM0101** [thiswillbeyourgithub/sleep_tracker_pinetime_wasp-os#6]
I found when trying to build the micropython.zip for  SleepTk that I was getting a makefile error,  `.text' will not fit in region `FLASH_TEXT'. 

The workaround was to delete applications that are not needed to free up space, so I:

Deleted 5 apps (.py) files from wasp/apps that weren't needed.
Commented out those apps from the wasp/boards manifest_240x240.py
Commented out those apps in the wasp/apps software.py
Re-ran ./tools/ota-dfu/dfu.py -z build-pinetime/micropython.zip -a XX:XX:XX:XX:XX:XX --legacy

I think WASP-OS's memory is near or at capacity and more folks will run into this error. In fact I will probably write a PR to WASP-OS and update their documentation...basically how to do a custom build.
Gary

**Comment by thiswillbeyourgithub** [comment]
Hi!

Thanks for the heads up, I'm aware that my app is quite large and over the limit of the default build.

Someone just started a PR about helping to do custom builds btw: [Wasp A La Carte](https://github.com/wasp-os/wasp-os/pull/403)
