### ISSUE TITLE
[Request] Wasp-os build with apps

### ISSUE THREAD

**Issue by tiPrans** [thiswillbeyourgithub/sleep_tracker_pinetime_wasp-os#7]
Hey there! 

Really love the Sleep Tracking app that you developed and how standalone it is. However, I'm stuck at building Wasp-os from the source code and would like to request if you could please share your build that includes the Sleep Tracker app that can be uploaded OTA to the PineTime (bootloader.zip & micropython.zip)? Maybe you could upload a build of your daily driver Wasp-os repository (if it contains SleepTk.py) would be great as it also seems to have some useful apps installed. 

Thanks and apologies for the dummy request!

**Comment by thiswillbeyourgithub** [comment]
I think you just need the micropython.zip file, do correct me if I'm wrong.

here it is 
[micropython.zip](https://github.com/thiswillbeyourgithub/sleep_tracker_pinetime_wasp-os/files/10948679/micropython.zip)


I'm very short on time so it's actually the quickest for me to help you and I'm fine with that :)

**Comment by tiPrans** [comment]
thanks a lot for your reply! I've uploaded the zip file and the OS seems to work, but there appears to be an issue with the SleepTk app. Tapping on it turns the screen into its negative colours and two bomb icons appear (seriously!). If I tap on the screen again, I get a traceback error :/ 

Also, I cannot seem to find the option to change watch face or find other apps on the menu. Only SleepTk, Pomodor, Alarm and Settings are there. And notifications aren't being mirrored by GadgetBridge :/

any help with providing an updated file please?

**Comment by thiswillbeyourgithub** [comment]
Show me the traceback please.

> Also, I cannot seem to find the option to change watch face or find other apps on the menu. Only SleepTk, Pomodor, Alarm and Settings are there. And notifications aren't being mirrored by GadgetBridge :/

I did numerous change to my wasp os build so this is "normal"

**Comment by tiPrans** [comment]
I see, are there any builds with the default apps and watch face as well as SleepTk? I find some of the other apps and the ability to receive notifications useful as well.

Please find the traceback in the images below (sorry for the screen smudges!):

![trcbck 1](https://user-images.githubusercontent.com/51713596/224492467-67e9e771-4252-405e-af44-46362d3c6d9f.jpg)

![trcbck 2](https://user-images.githubusercontent.com/51713596/224492474-0effdc0e-2781-403d-b376-22fa20ff6624.jpg)

![trcbck 3](https://user-images.githubusercontent.com/51713596/224492483-20f8b204-1d9a-4bed-abc9-9453ebdc81f9.jpg)

**Comment by thiswillbeyourgithub** [comment]
I'm really sorry but I have no idea how it's possible to have an issue with this zip as it's the one I'm using daily!

I really don't have the time to dig in the commits of wapos that are needed for SleepTk ~~so I can't help you. If you really are motivated and want to learn along the way your best bet would be to add the SleepTk python to your waspos build and figure out from the traceback which commits of wapos are needed based on what I did.~~

Actually I just did a quick tests and changed a few things and SleepTk seems to be working now on the latest wasp in the simulator! I just added a few checks to avoid looking for "get" and "set" method of wasp.

Can you try it on the default build on your watch and report back? If it's working I will gladely push it over as an extra app in wasp os :)

thanks

**Comment by tiPrans** [comment]
hey there, thanks a lot for looking further into this! could you please send the micropython.zip file of the build that I should test? making this file is where I am stuck at (as I am not much of a programmer) and sorry for the dummy request! But if you can share it, I'll be happy to test it on my watch and report back!

**Comment by thiswillbeyourgithub** [comment]
[micropython.zip](https://github.com/thiswillbeyourgithub/sleep_tracker_pinetime_wasp-os/files/10950937/micropython.zip)

**Comment by tiPrans** [comment]
thanks a lot! Just uploaded it to my watch and tried the app. Happy to report that it's fully functional now! I can access the app, adjust the settings and start tracking. Thanks for fixing it!

Is there any chance to please provide a new micropython.zip wasp-os build with SleepTk as well as the default apps?

**Comment by thiswillbeyourgithub** [comment]
I updated the PR

**Comment by tiPrans** [comment]
thanks! Could you please share the micropython.zip when you are able to build it from the main os?

**Comment by thiswillbeyourgithub** [comment]
No because it's slightly too large. You just have to remove some default apps, it's explained in the doc

**Comment by tiPrans** [comment]
My dummy issue is exactly with building the micropython.zip and I could do without some of the apps such as sports, haiku and fibonacci_clock.py. Any assistance would be very much appreciated!

**Comment by thiswillbeyourgithub** [comment]
The matrix channels are more appropriate then. The docs are great too
